In [1]:
from pymongo import MongoClient
import pandas as pd

In [2]:
connection_string = "mongodb+srv://EZ-Home:EZ-Home2026@cluster0.hmnsg6m.mongodb.net/EZ-Home"

client = MongoClient(connection_string)

db = client["EZ-Home"]

Carts

In [4]:
collection = db["carts"]

data = list(collection.find())

carts = pd.DataFrame(data)

carts

,_id,user,items,totalPrice,createdAt,updatedAt,__v
0,69a645e364582af9bf0b15df,6985fe8c62a018c08e2b75c7,[],0,2026-03-03 02:22:27.726,2026-03-03 03:37:15.807,2
1,69a6461464582af9bf0b15e6,69a50b8f53480eb173e7aa23,"[{'product': 69a471eaabdc42732b86d00e, 'qty': ...",94,2026-03-03 02:23:16.722,2026-03-07 04:43:28.606,54
2,69a650ffbbdbff50475315e5,699fbf5758a847eaacd5fad6,[],0,2026-03-03 03:09:51.042,2026-03-07 02:17:47.015,29
3,69ab6a28e8ee624c3f0b1bbb,69ab69fbe8ee624c3f0b1ba2,[],0,2026-03-06 23:58:32.459,2026-03-06 23:59:15.248,4

Categories

In [5]:
collection = db["categories"]

data = list(collection.find())

categories = pd.DataFrame(data)

categories

,_id,name,createdAt,updatedAt,__v
0,69a3575faf07651683a5625e,ماكنات قهوة,2026-02-28 21:00:15.452,2026-03-01 03:15:02.895,0
1,69a3b1208c8945d5352cc19a,قلاية هوائية,2026-03-01 03:23:12.505,2026-03-01 03:23:12.505,0
2,69a50a612fa6e5dabe615272,مطحنة بهارات,2026-03-02 03:56:17.045,2026-03-02 03:56:17.045,0

Orders

In [7]:
collection = db["orders"]

data = list(collection.find())

orders = pd.DataFrame(data)

orders

,_id,user,customer,items,total,status,createdAt,updatedAt,__v
0,69a23217d027030627e41aee,6985fe8c62a018c08e2b75c7,"{'fullName': 'Abdallah Faheem', 'phone': '0096...","[{'product': 699de1b97cba9532265758ee, 'produc...",498,pending,2026-02-28 00:08:55.416,2026-02-28 00:08:55.416,0
1,69a23242d027030627e41b09,6985fe8c62a018c08e2b75c7,"{'fullName': 'Abdallah Faheem', 'phone': '0096...","[{'product': 699de1b97cba9532265758ee, 'produc...",498,paid,2026-02-28 00:09:38.582,2026-03-06 03:04:30.601,0
2,69a233f5d027030627e41b32,6985fe8c62a018c08e2b75c7,"{'fullName': 'Abdallah Faheem', 'phone': '0096...","[{'product': 699de1b97cba9532265758ee, 'produc...",498,pending,2026-02-28 00:16:53.210,2026-03-06 03:03:53.258,0
3,69aa4b9d688508823e6310e7,69a50b8f53480eb173e7aa23,"{'fullName': 'Zarifeh User', 'phone': '0096279...","[{'product': 69a3b23a8c8945d5352cc1a4, 'produc...",381,paid,2026-03-06 03:35:57.689,2026-03-06 04:02:16.330,0
4,69aa51b0688508823e6311e1,69a50b8f53480eb173e7aa23,"{'fullName': 'Zarifeh User', 'phone': '0096279...","[{'product': 69a3b23a8c8945d5352cc1a4, 'produc...",316,pending,2026-03-06 04:01:52.891,2026-03-06 04:01:52.891,0
5,69aab7261f2680478a033240,69a50b8f53480eb173e7aa23,"{'fullName': 'Zarifeh User', 'phone': '0096279...","[{'product': 69a3b23a8c8945d5352cc1a4, 'produc...",99,pending,2026-03-06 11:14:46.475,2026-03-06 11:14:46.475,0
6,69aae69ab2ff8d22164db2c9,699fbf5758a847eaacd5fad6,"{'fullName': 'Abood', 'phone': '00962788688926...","[{'product': 69a3b5fd8c8945d5352cc20f, 'produc...",197,pending,2026-03-06 14:37:14.078,2026-03-06 14:38:06.379,0
7,69ab5ad7a105e953cf991dd4,699fbf5758a847eaacd5fad6,"{'fullName': 'Abood', 'phone': '00962788688926...","[{'product': 69a3b23a8c8945d5352cc1a4, 'produc...",99,paid,2026-03-06 22:53:11.089,2026-03-06 23:29:00.637,0
8,69ab6304955c0fd02e58fd6a,699fbf5758a847eaacd5fad6,"{'fullName': 'Abood', 'phone': '00962788688926...","[{'product': 69a74bdcd6e1ccc296be0ddb, 'produc...",75,paid,2026-03-06 23:28:04.803,2026-03-06 23:28:42.712,0
9,69ab6a53e8ee624c3f0b1d1f,69ab69fbe8ee624c3f0b1ba2,"{'fullName': 'AmmarAlharoun', 'phone': '009627...","[{'product': 69a474a2abdc42732b86d052, 'produc...",519,paid,2026-03-06 23:59:15.026,2026-03-06 23:59:43.152,0
10,69ab79c4b560f0e079e6b3f0,69a50b8f53480eb173e7aa23,"{'fullName': 'Mohammed Zarifeh user', 'phone':...","[{'product': 69a3a4bb4040e178b3dd3e6d, 'produc...",158,pending,2026-03-07 01:05:08.197,2026-03-07 01:05:08.197,0
11,69ab8aca0ddda2282895a77e,699fbf5758a847eaacd5fad6,"{'fullName': 'Abood', 'phone': '00962788688926...","[{'product': 69a3a4bb4040e178b3dd3e6d, 'produc...",59,pending,2026-03-07 02:17:46.790,2026-03-07 02:17:46.790,0

Products

In [9]:
collection = db["products"]

data = list(collection.find())

products = pd.DataFrame(data)

products

,_id,name,price,description,image,category,stock,createdAt,updatedAt,__v
0,69a3a4bb4040e178b3dd3e6d,مقلاة هوائية كونتي 8 لتر,59,"🍟 أكل مقرمش… وصحي أكتر 🍗✨ \n1750 واط, 8 لتر, ...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3b1208c8945d5352cc19a,10,2026-03-01 02:30:19.991,2026-03-01 03:39:30.640,0
1,69a3b23a8c8945d5352cc1a4,مقلاة هوائية وفرن كونتي 25 لتر,99,"🍟 أكل مقرمش… وصحي أكتر 🍗✨ \n2100واط, \n25لتر,...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3b1208c8945d5352cc19a,15,2026-03-01 03:27:54.761,2026-03-01 03:35:22.607,0
2,69a3b5fd8c8945d5352cc20f,مقلاة هوائية كونتي 8 لتر,59,"🍟 أكل مقرمش… وصحي أكتر 🍗✨ \n1750 واط, 8 لتر, ...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3b1208c8945d5352cc19a,15,2026-03-01 03:43:57.672,2026-03-02 03:01:43.245,0
3,69a471eaabdc42732b86d00e,ماكنة قهوة كبسولات سايونا,69,"لأن القهوة مو مجرد مشروب… هي مزاج\n1450واط, 60...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3575faf07651683a5625e,20,2026-03-01 17:05:46.103,2026-03-01 18:54:06.044,0
4,69a474a2abdc42732b86d052,ماكنة قهوة كبسولات سايونا,69,"لأن القهوة مو مجرد مشروب… هي مزاج\n1400واط, 60...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3575faf07651683a5625e,15,2026-03-01 17:17:22.189,2026-03-01 18:54:20.627,0
5,69a48a6bbea45e6698e37b23,ماكنة تحضير قهوة كبسولات سايونا,105,"لأن القهوة مو مجرد مشروب… هي مزاج\n1450واط, 1 ...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3575faf07651683a5625e,20,2026-03-01 18:50:19.248,2026-03-01 18:54:25.355,0
6,69a48c4dbea45e6698e37bce,ماكنة تحضير قهوة تركي سايونا,105,"لأن القهوة مو مجرد مشروب… هي مزاج\n700 واط, 80...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3575faf07651683a5625e,18,2026-03-01 18:58:21.874,2026-03-01 19:03:27.451,0
7,69a48e80bea45e6698e37be4,ماكنة تحضير قهوة اسبريسو سوناتشي,59,"لأن القهوة مو مجرد مشروب… هي مزاج\n850 واط, 1 ...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3575faf07651683a5625e,14,2026-03-01 19:07:44.128,2026-03-01 19:07:44.128,0
8,69a48ef6bea45e6698e37bf5,ماكنة تحضير قهوة اسبريسو سوناتشي,65,"لأن القهوة مو مجرد مشروب… هي مزاج\n850 واط, 1...",https://res.cloudinary.com/dlasg8oto/image/upl...,69a3575faf07651683a5625e,10,2026-03-01 19:09:42.732,2026-03-01 19:10:58.244,0
9,69a74bdcd6e1ccc296be0ddb,مطحنة 150 غرام صناعي,25,بهارات مطحونة بدقة صناعية، جودة ثابتة، ونكهة ل...,https://res.cloudinary.com/dlasg8oto/image/upl...,69a50a612fa6e5dabe615272,10,2026-03-03 21:00:12.555,2026-03-03 21:00:42.333,0

Users

In [10]:
collection = db["users"]

data = list(collection.find())

users = pd.DataFrame(data)

users

,_id,fullName,phone,password,role,createdAt,updatedAt,__v
0,6985fe8c62a018c08e2b75c7,Abdallah Faheem,00962788688925,$2b$10$Q45e1A82FEXMMayPNMMecO3l0Nw42cWwycvAlXr...,admin,2026-02-06 14:45:32.615,2026-02-26 03:37:26.549,0
1,698697083fafec4ab8370d8c,Murad Faheem,00962786702296,$2b$10$mlaZdDwbEwJKvQMrwCl/hO0qYNg7YyPAYz1hA/8...,admin,2026-02-07 01:36:08.464,2026-02-07 13:01:03.331,0
2,699fbf5758a847eaacd5fad6,Abood,00962788688926,$2b$10$YBpJFGTdUUYVT2iPm42U/O8kxzmK94l8jK7HpCv...,user,2026-02-26 03:34:47.913,2026-02-26 03:34:47.913,0
3,69a10d78d826f5ff31ee0400,Mohammed Zarifeh,00962792900159,$2b$10$5fPEjGl3c78jHQ4RKJQoyeKdCJO13g8Kr5yPfze...,admin,2026-02-27 03:20:24.753,2026-02-27 03:20:24.753,0
4,69a50b8f53480eb173e7aa23,Mohammed Zarifeh user,00962791111111,$2b$10$4T/A43177yM1HRrGnq3Q4OvmvfaivJDzBiuOOMA...,user,2026-03-02 04:01:19.246,2026-03-06 11:19:39.075,0
5,69ab69fbe8ee624c3f0b1ba2,AmmarAlharoun,00962791437684,$2b$10$9MVvqXEUU1Mvn3lr7evB6uSzx2WEnrExIy44u0C...,user,2026-03-06 23:57:47.106,2026-03-06 23:57:47.106,0

Wishlists

In [11]:
collection = db["wishlists"]

data = list(collection.find())

wishlists = pd.DataFrame(data)

wishlists

,_id,user,products,createdAt,updatedAt,__v
0,69a1e436fd35d1be6d4c7716,6985fe8c62a018c08e2b75c7,"[69a12249d826f5ff31ee0493, 699de1b97cba9532265...",2026-02-27 18:36:38.616,2026-02-27 22:17:18.365,6
1,69a7b1604560b4d6e22f63bf,69a50b8f53480eb173e7aa23,"[69a3b5fd8c8945d5352cc20f, 69a3b23a8c8945d5352...",2026-03-04 04:13:20.237,2026-03-07 04:47:06.483,60
2,69a842d85ba1b11823f902d4,69a10d78d826f5ff31ee0400,[],2026-03-04 14:34:00.873,2026-03-04 14:34:01.369,2
3,69a89040f1e752ee13ab4e6e,699fbf5758a847eaacd5fad6,"[69a3b5fd8c8945d5352cc20f, 69a3a4bb4040e178b3d...",2026-03-04 20:04:16.672,2026-03-06 22:53:36.525,6
4,69ab6a0fe8ee624c3f0b1baa,69ab69fbe8ee624c3f0b1ba2,"[69a3b23a8c8945d5352cc1a4, 69a3a4bb4040e178b3d...",2026-03-06 23:58:07.505,2026-03-06 23:58:30.580,2